### ISSUE TITLE
How to use js to release tconsole？

### ISSUE THREAD

**Issue by pony5551** [tondrej/chakracore-delphi#4]
var c = new Console();
//How to release here？
delete c;//?
c = null;//?

**Comment by tondrej** [comment]
`c = null;` works, as well as `c = 42;`. Just by assigning the variable a different value the previously stored instance's reference count is automatically decreased by ChakraCore, and later when the garbage collector sees 0 reference count it will call the [registered](https://github.com/tondrej/chakracore-delphi/blob/246a5d82374687f5fe8d7692a4a3becd18cf04eb/src/ChakraCoreClasses.pas#L1593) [finalizer](https://github.com/tondrej/chakracore-delphi/blob/246a5d82374687f5fe8d7692a4a3becd18cf04eb/src/ChakraCoreClasses.pas#L399) callback which in turn frees the instance.

**Comment by pony5551** [comment]
c=null;
But this does not release the object!

**Comment by tondrej** [comment]
> c=null;
> But this does not release the object!
> 

Not immediately - but that's by design. [GC](https://github.com/Microsoft/ChakraCore/wiki/Architecture-Overview#garbage-collector) releases the object eventually. (It might be a good idea to extend the test suite with a proof.)

If you think you've found a bug please provide a [MCVE](https://stackoverflow.com/help/mcve).
Thanks!

From my own experiments it works as expected. All native instances are released, either by the GC at some point during execution of the script or at the latest when the runtime is disposed.

**Comment by pony5551** [comment]
I don't see where to call TNativeObject.AddRef and TNativeObject.Release！

In my opinion, is TNativeObject designed as an interface more appropriate?
Because now you don't have to call JsDisposeRuntime and all of your new objects won't be thrown!

**Comment by pony5551** [comment]
Maybe my idea is not necessarily correct, maybe you have other better way!

**Comment by pony5551** [comment]
procedure Main;
var
  DataModule: TDataModuleMain;
begin
  ShowInfo;

  DataModule := TDataModuleMain.Create(nil);
  try
    DataModule.Execute(ParamStrings);
    ReadLn; //**At this point, new Console() is not released**
  finally
    DataModule.Free;
    //**When you get here, new Console() is released**
  end;
end;

**Comment by tondrej** [comment]
I'm closing this issue with "works as designed". Please see the new finalizer tests in 48bea58.
